# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8628f454b27ced162cb84198f06768de2550b1aaa0f7fa51ca7ffb156592af5937043bb2f12b5ea50acf0069f040db05eca76427171fe586c9ceba8efa708386

test:
  secret_key_base: 7c9c481f90516dc13cf7e55d9ac943f15615df4889af34a987bec5af3fa1c1131351fd23460a0eeb65b403ebb1073e25b77fef86a88f52b336bad418e67acf7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
